site_name: Shift Software
repo_url: https://github.com/ShiftSoftware
repo_name: ShiftSoftware/Website
site_author: Shift Software
edit_uri: edit/master/ShiftSoftware/docs/
site_description: >-
  TypeAuth
copyright: Copyright &copy; 2022 Shift Software
default: getting-started
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
nav:
    - Home: 'index.md'
    - About: 
        - Strategy & Vision: 'about/strategy-and-vision.md'
        - Code of Conduct: 'about/code-of-conduct.md'
        - Developers: 'about/developers.md'
    - Philosophy:
        - Philosophy:      'philosophy/philosophy.md'
        - Characteristics: 'philosophy/characteristics.md'
    - Software Development: 
        - Tasks:                             'software-development/tasks.md'
        - Continuous Integration:            'software-development/continuous-integration.md'
        - Automated Testing:                 'software-development/automated-testing.md'
        - Continuous Delivery:               'software-development/continuous-delivery.md'
        - Active Maintenance:                'software-development/active-maintenance.md'
    #- Clients: 'clients.md'
extra_css:
  - overrides/css/extra.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ShiftSoftware
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/shift.software
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/shift-software
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/the.shift.software

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.mark
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true